# Generated by Django 6.1.1 on 2026-09-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chowly', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('bartender_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bartenders', to='chowly.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefs', to='chowly.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='chowly.restaurant')),
            ],
        ),
    ]
