# Generated by Django 6.1.1 on 2026-09-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chowly', '0003_bartender_chef_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='chowly.restaurant')),
            ],
        ),
    ]
