# Generated by Django 6.1.1 on 2026-09-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chowly', '0006_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_details', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating from 1 to 5', null=True)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='chowly.order')),
            ],
        ),
    ]
