# Generated by Django 6.1.1 on 2026-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chowly', '0015_order_completed_at_order_served_at_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Optional customer rating from 1 to 5', null=True),
        ),
    ]
