# Generated by Django 6.1.1 on 2026-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chowly', '0016_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
