# Generated by Django 6.1.1 on 2026-09-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chowly', '0017_alter_customer_email_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
